variables:
  BuildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  skipComponentGovernanceDetection: true
  ANDROID_APP_CENTER_SECRET: asdf
  IOS_APP_CENTER_SECRET: asdf

jobs:
  - job: 'AndroidBuild'
    pool:
      name: Azure Pipelines
      vmImage: 'macos-latest'
      demands:
        - msbuild
        - MSBuild
        - Xamarin.Android
        - JDK

    steps:
    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 4.4.1'
      inputs:
        versionSpec: 4.4.1

    - task: Boots@1
      displayName: 'Install Android 16.3'
      inputs:
        uri: https://aka.ms/xamarin-android-commercial-d16-3-macos      

    - task: MSBuild@1
      displayName: 'Restore NuGets'
      inputs:
        solution: '**/*TailwindTraders.Mobile.Android.csproj'
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '-t:Restore'

    - task: DownloadSecureFile@1
      displayName: 'Downloading google-services.json from Secure Storage'
      name: googleservices
      inputs:
        secureFile: 'google-services.json'

    - task: CopyFiles@2
      displayName: 'Copying over google-services.json'
      inputs:
        SourceFolder: '$(Agent.TempDirectory)'
        Contents: 'google-services.json'
        TargetFolder: '$(Build.SourcesDirectory)/src/TailwindTraders.Mobile/TailwindTraders.Mobile.Android'
        OverWrite: true

    - task: Bash@3
      displayName: 'cat google-services.json'
      inputs:
        targetType: 'inline'
        script: 'cat $(Build.SourcesDirectory)/src/TailwindTraders.Mobile/TailwindTraders.Mobile.Android/google-services.json'

    - task: Bash@3
      inputs:
        filePath: '$(BUILD.SOURCESDIRECTORY)/appcenter-secrets-replace.sh'

    - task: XamarinAndroid@1
      displayName: 'Build Droid'
      inputs:
        projectFile: '**/*TailwindTraders.Mobile.Android.csproj'
        outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
        configuration: '$(BuildConfiguration)'
        jdkOption: 'JDKVersion'

    - task: CopyFiles@2
      displayName: 'Copy APK file to staging'
      inputs:
        SourceFolder: '$(build.binariesdirectory)/$(BuildConfiguration)'
        Contents: '**/*.apk'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'      

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Android APK'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'      

  - job: 'iOSBuild'
    pool:
      name: Azure Pipelines
      vmImage: 'macos-latest'
      demands:
        - msbuild
        - MSBuild
        - Xamarin.iOS
        - xcode
        
    steps:
    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 4.4.1'
      inputs:
        versionSpec: 4.4.1
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'CodeMillDevelopment1.p12'
        certPwd: 'coupon_stolen_armload'
        keychain: 'temp'
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'Tailwind_Traders_Cleaned_DEV.mobileprovision'
    
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*TailwindTraders.iOS.sln'
        feedsToUse: 'select'

    #- task: Bash@3
    #  inputs:
    #    targetType: 'inline'
    #    script: 'sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_18_1'

    - task: Boots@1
      inputs:
        uri: 'https://download.mono-project.com/archive/6.6.0/macos-10-universal/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg'

    #- task: Boots@1
    #  inputs:
    #    uri: 'https://download.visualstudio.microsoft.com/download/pr/5a678460-107f-4fcf-8764-80419bc874a0/3f78c6826132f6f8569524690322adba/xamarin.ios-13.8.1.17.pkg'

    #- task: XamariniOS@2
    #  inputs:
    #    solutionFile: '**/*TailwindTraders.iOS.sln'
    #    configuration: '$(BuildConfiguration)'
    #    packageApp: true
    #    runNugetRestore: false
    #    signingIdentity: 'iPhone Developer: Matthew Soucoup (HQER4F7A36)'
    #    signingProvisioningProfileID: '8e1eb329-d4c3-42de-9182-a7a5ba712866'

    