pool:
  name: Azure Pipelines
  vmImage: 'macos-latest'
  demands:
  - msbuild
  - MSBuild
  - Xamarin.Android
  - JDK

variables:
  BuildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: Boots@1
  displayName: 'Install Mono 6.5'
  inputs:
    uri: https://download.mono-project.com/archive/6.4.0/macos-10-universal/MonoFramework-MDK-6.4.0.198.macos10.xamarin.universal.pkg

- task: Boots@1
  displayName: 'Install Android 16.3'
  inputs:
    uri: https://aka.ms/xamarin-android-commercial-d16-3-macos

- task: Boots@1
  displayName: 'Install iOS 13'
  inputs:
    uri: https://download.visualstudio.microsoft.com/download/pr/5a678460-107f-4fcf-8764-80419bc874a0/3f78c6826132f6f8569524690322adba/xamarin.ios-13.8.1.17.pkg

- task: MSBuild@1
  inputs:
    solution: '**/*TailwindTraders.Mobile.Android.csproj'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '-t:Restore'